In [1]:
import numpy as np
import pandas as pd
import dask.dataframe as dd
import glob
import os

In [2]:
pwd

'/Users/dawn.urycki/Desktop/Local_repos/stream-temp'

### Covariates

In [3]:
%load_ext rpy2.ipython

In [4]:
%%R
install.packages("fst")

R[write to console]: Installing package into ‘/Users/dawn.urycki/Library/R/x86_64/4.3/library’
(as ‘lib’ is unspecified)

--- Please select a CRAN mirror for use in this session ---
Secure CRAN mirrors

 1: 0-Cloud [https]                   2: Australia (Canberra) [https]
 3: Australia (Melbourne 1) [https]   4: Australia (Melbourne 2) [https]
 5: Austria (Wien) [https]            6: Belgium (Brussels) [https]
 7: Brazil (PR) [https]               8: Brazil (SP 1) [https]
 9: Brazil (SP 2) [https]            10: Bulgaria [https]
11: Canada (MB) [https]              12: Canada (ON 1) [https]
13: Canada (ON 2) [https]            14: Chile (Santiago) [https]
15: China (Beijing 1) [https]        16: China (Beijing 2) [https]
17: China (Beijing 3) [https]        18: China (Hefei) [https]
19: China (Hong Kong) [https]        20: China (Lanzhou) [https]
21: China (Nanjing) [https]          22: China (Shanghai 2) [https]
23: China (Shenzhen) [https]         24: China (Wuhan) [https]
25: Costa Rica [https]               26: Cyprus [https]
27: Denmark [https]                  28: East Asia [https]
29: Ecuador (Cuenca) [https]         30: Finland (Helsinki) [https]
31: France (Lyon 1) [https]          32: France (Lyon 2) [https]
33: France (Paris 1) [https]         34: Germany (Erlangen) [https]
35: Germany (Göttingen) [https]      36: Germany (Leipzig) [https]
37: Germany (Münster) [https]        38: Greece [https]
39: Hungary [https]                  40: Iceland [https]
41: India (Bengaluru) [https]        42: India (Bhubaneswar) [https]
43: India (New Delhi) [https]        44: Indonesia (Banda Aceh) [https]
45: Iran (Mashhad) [https]           46: Italy (Milano) [https]
47: Italy (Padua) [https]            48: Japan (Yonezawa) [https]
49: Korea (Gyeongsan-si) [https]     50: Mexico (Mexico City) [https]
51: Mexico (Texcoco) [https]         52: Morocco [https]
53: Netherlands (Dronten) [https]    54: New Zealand [https]
55: Saudi Arabia (Riyadh) [https]    56: Spain (A Coruña) [https]
57: Spain (Madrid) [https]           58: Sweden (Umeå) [https]
59: Switzerland (Zurich 1) [https]   60: Taiwan (Taipei) [https]
61: UK (Bristol) [https]             62: UK (London 1) [https]
63: USA (IA) [https]                 64: USA (MI) [https]
65: USA (MO) [https]                 66: USA (OH) [https]
67: USA (OR) [https]                 68: USA (PA 1) [https]
69: USA (TN) [https]                 70: USA (UT) [https]
71: United Arab Emirates [https]     72: Uruguay [https]
73: (other mirrors)

Selection:  67

R[write to console]: trying URL 'https://ftp.osuosl.org/pub/cran/src/contrib/fst_0.9.8.tar.gz'

R[write to console]: Content type 'application/x-gzip'
R[write to console]:  length 274495 bytes (268 KB)

R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]:

R[write to console]: downloaded 268 KB


* installing *source* package ‘fst’ ...
** package ‘fst’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
using C++ compiler: ‘clang version 20.1.7’
using SDK: ‘MacOSX15.2.sdk’

x86_64-apple-darwin13.4.0-clang++ -std=gnu++17 -I"/opt/miniconda3/envs/temp-data-env/lib/R/include" -DNDEBUG  -I'/Users/dawn.urycki/Library/R/x86_64/4.3/library/Rcpp/include' -I'/Users/dawn.urycki/Library/R/x86_64/4.3/library/fstcore/include' -D_FORTIFY_SOURCE=2 -isystem /opt/miniconda3/envs/temp-data-env/include -mmacosx-version-min=10.13 -mmacosx-version-min=10.13 -I/opt/miniconda3/envs/temp-data-env/include    -fPIC  -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem /opt/miniconda3/envs/temp-data-env/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1747311155079/work=/usr/local/src/conda/r-base-4.3.3 -fdebug-prefix-map=/opt/miniconda3/envs/temp-data-env=/usr/local/src/conda-prefix  -c RcppExports.cpp -o RcppExports.o
x86_64-apple-darwin13.4.0-clang++ -std=gnu++17 -I"/opt/miniconda3/envs/temp-data-env/lib/R/include" -DNDEBUG  -I'/Users/dawn.urycki/Library/R/x86_64/4.3/library/Rcpp/include' -I'/Users/dawn.urycki/Library/R/x86_64/4.3/library/fstcore/include' -D_FORTIFY_SOURCE=2 -isystem /opt/miniconda3/envs/temp-data-env/include -mmacosx-version-min=10.13 -mmacosx-version-min=10.13 -I/opt/miniconda3/envs/temp-data-env/include    -fPIC  -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem /opt/miniconda3/envs/temp-data-env/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1747311155079/work=/usr/local/src/conda/r-base-4.3.3 -fdebug-prefix-map=/opt/miniconda3/envs/temp-data-env=/usr/local/src/conda-prefix  -c flex_store.cpp -o flex_store.o
x86_64-apple-darwin13.4.0-clang++ -std=gnu++17 -I"/opt/miniconda3/envs/temp-data-env/lib/R/include" -DNDEBUG  -I'/Users/dawn.urycki/Library/R/x86_64/4.3/library/Rcpp/include' -I'/Users/dawn.urycki/Library/R/x86_64/4.3/library/fstcore/include' -D_FORTIFY_SOURCE=2 -isystem /opt/miniconda3/envs/temp-data-env/include -mmacosx-version-min=10.13 -mmacosx-version-min=10.13 -I/opt/miniconda3/envs/temp-data-env/include    -fPIC  -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem /opt/miniconda3/envs/temp-data-env/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1747311155079/work=/usr/local/src/conda/r-base-4.3.3 -fdebug-prefix-map=/opt/miniconda3/envs/temp-data-env=/usr/local/src/conda-prefix  -c fst_compress.cpp -o fst_compress.o
x86_64-apple-darwin13.4.0-clang++ -std=gnu++17 -I"/opt/miniconda3/envs/temp-data-env/lib/R/include" -DNDEBUG  -I'/Users/dawn.urycki/Library/R/x86_64/4.3/library/Rcpp/include' -I'/Users/dawn.urycki/Library/R/x86_64/4.3/library/fstcore/include' -D_FORTIFY_SOURCE=2 -isystem /opt/miniconda3/envs/temp-data-env/include -mmacosx-version-min=10.13 -mmacosx-version-min=10.13 -I/opt/miniconda3/envs/temp-data-env/include    -fPIC  -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem /opt/miniconda3/envs/temp-data-env/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1747311155079/work=/usr/local/src/conda/r-base-4.3.3 -fdebug-prefix-map=/opt/miniconda3/envs/temp-data-env=/usr/local/src/conda-prefix  -c openmp.cpp -o openmp.o
x86_64-apple-darwin13.4.0-clang++ -std=gnu++17 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/opt/miniconda3/envs/temp-data-env/lib/R/lib -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/opt/miniconda3/envs/temp-data-env/lib -L/opt/miniconda3/envs/temp-data-env/lib -o fst.dylib RcppExports.o flex_store.o fst_compress.o openmp.o -L/opt/miniconda3/envs/temp-data-env/lib/R/lib -lR -Wl,-framework -Wl,CoreFoundation

installing to /Users/dawn.urycki/Library/R/x86_64/4.3/library/00LOCK-fst/00new/fst/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (fst)
R[write to console]:

R[write to console]:
R[write to console]: The downloaded source packages are in
	‘/private/var/folders/95/99dy_ns968195cnlvp5xhwqm0000gp/T/Rtmp9mAEHn/downloaded_packages’
R[write to console]:
R[write to console]:

In [5]:
%%R
library(fst)
getwd()

R[write to console]: fst package v0.9.8

[1] "/Users/dawn.urycki/Desktop/Local_repos/stream-temp"

In [6]:
import rpy2.robjects as ro
from rpy2.robjects import pandas2ri
pandas2ri.activate()

In [7]:
dir_to_do = os.path.join('DATA', 'Inputs', 'gcms', 'predictions_covariates')
subdirs = glob.glob(dir_to_do + '*/*/')
subdirs.sort(key = str.lower)
subdirs = subdirs[:-1]
subdirs

['DATA/Inputs/gcms/predictions_covariates/CanESM2/',
 'DATA/Inputs/gcms/predictions_covariates/CCSM4/',
 'DATA/Inputs/gcms/predictions_covariates/CNRM-CM5/',
 'DATA/Inputs/gcms/predictions_covariates/CSIRO-Mk3-6-0/',
 'DATA/Inputs/gcms/predictions_covariates/GDFL-ESM2M/',
 'DATA/Inputs/gcms/predictions_covariates/HadGEM2-CC/',
 'DATA/Inputs/gcms/predictions_covariates/HadGEM2-ES/',
 'DATA/Inputs/gcms/predictions_covariates/inmcm4/',
 'DATA/Inputs/gcms/predictions_covariates/IPSL-CM5A-MR/',
 'DATA/Inputs/gcms/predictions_covariates/MIROC/']

In [8]:
gcms = [s.split('/')[-2] for s in subdirs]
#gcms.sort(key = str.lower)
gcms

['CanESM2',
 'CCSM4',
 'CNRM-CM5',
 'CSIRO-Mk3-6-0',
 'GDFL-ESM2M',
 'HadGEM2-CC',
 'HadGEM2-ES',
 'inmcm4',
 'IPSL-CM5A-MR',
 'MIROC']

In [9]:
gcm_dict = {it:i+1 for i, it in enumerate(gcms)}
gcm_dict

{'CanESM2': 1,
 'CCSM4': 2,
 'CNRM-CM5': 3,
 'CSIRO-Mk3-6-0': 4,
 'GDFL-ESM2M': 5,
 'HadGEM2-CC': 6,
 'HadGEM2-ES': 7,
 'inmcm4': 8,
 'IPSL-CM5A-MR': 9,
 'MIROC': 10}

In [10]:
for i in range(len(subdirs)): print(len(glob.glob(subdirs[i] + '/*')))

369
369
370
369
369
369
369
375
369
369

In [13]:
files_to_do = [s.split('/')[-1] for s in glob.glob(subdirs[0] + '/*')]
files_to_do.sort()
files_to_do

['huc_1701010111.fst',
 'huc_1701010113.fst',
 'huc_1701010117.fst',
 'huc_1701010304.fst',
 'huc_1701010305.fst',
 'huc_1701010401.fst',
 'huc_1701010404.fst',
 'huc_1701010406.fst',
 'huc_1701010407.fst',
 'huc_1701010504.fst',
 'huc_1701010505.fst',
 'huc_1701020102.fst',
 'huc_1701020211.fst',
 'huc_1701020213.fst',
 'huc_1701020406.fst',
 'huc_1701020507.fst',
 'huc_1701020605.fst',
 'huc_1701020606.fst',
 'huc_1701020701.fst',
 'huc_1701020702.fst',
 'huc_1701020703.fst',
 'huc_1701020704.fst',
 'huc_1701020705.fst',
 'huc_1701020801.fst',
 'huc_1701020802.fst',
 'huc_1701020803.fst',
 'huc_1701020804.fst',
 'huc_1701020901.fst',
 'huc_1701020902.fst',
 'huc_1701020903.fst',
 'huc_1701020905.fst',
 'huc_1701020906.fst',
 'huc_1701020907.fst',
 'huc_1701021001.fst',
 'huc_1701021003.fst',
 'huc_1701021004.fst',
 'huc_1701021005.fst',
 'huc_1701021101.fst',
 'huc_1701021102.fst',
 'huc_1701021103.fst',
 'huc_1701021104.fst',
 'huc_1701021201.fst',
 'huc_1701021202.fst',
 'huc_1701021203.fst',
 'huc_1701021204.fst',
 'huc_1701021206.fst',
 'huc_1701021207.fst',
 'huc_1701021208.fst',
 'huc_1701021301.fst',
 'huc_1701021302.fst',
 'huc_1701021303.fst',
 'huc_1701021304.fst',
 'huc_1701021305.fst',
 'huc_1701021306.fst',
 'huc_1701021309.fst',
 'huc_1701021310.fst',
 'huc_1701021311.fst',
 'huc_1701021312.fst',
 'huc_1701021313.fst',
 'huc_1701021401.fst',
 'huc_1701021402.fst',
 'huc_1701021502.fst',
 'huc_1701021503.fst',
 'huc_1701021604.fst',
 'huc_1701021609.fst',
 'huc_1701030202.fst',
 'huc_1701030406.fst',
 'huc_1702000110.fst',
 'huc_1702000111.fst',
 'huc_1702000112.fst',
 'huc_1702000113.fst',
 'huc_1702000114.fst',
 'huc_1702000115.fst',
 'huc_1702000116.fst',
 'huc_1702000117.fst',
 'huc_1702000119.fst',
 'huc_1702000209.fst',
 'huc_1702000212.fst',
 'huc_1702000213.fst',
 'huc_1702000217.fst',
 'huc_1702000219.fst',
 'huc_1702000220.fst',
 'huc_1702000303.fst',
 'huc_1702000401.fst',
 'huc_1702000615.fst',
 'huc_1702000618.fst',
 'huc_1702000619.fst',
 'huc_1702000620.fst',
 'huc_1702000621.fst',
 'huc_1702000622.fst',
 'huc_1702000701.fst',
 'huc_1702000713.fst',
 'huc_1702000718.fst',
 'huc_1702000719.fst',
 'huc_1702000720.fst',
 'huc_1702000806.fst',
 'huc_1702000807.fst',
 'huc_1702001106.fst',
 'huc_1702001307.fst',
 'huc_1702001401.fst',
 'huc_1702001403.fst',
 'huc_1702001509.fst',
 'huc_1702001510.fst',
 'huc_1702001606.fst',
 'huc_1703000105.fst',
 'huc_1703000201.fst',
 'huc_1703000203.fst',
 'huc_1703000305.fst',
 'huc_1704010302.fst',
 'huc_1704010401.fst',
 'huc_1704010403.fst',
 'huc_1704010404.fst',
 'huc_1704010407.fst',
 'huc_1704010409.fst',
 'huc_1704020103.fst',
 'huc_1704020202.fst',
 'huc_1704020205.fst',
 'huc_1704020207.fst',
 'huc_1704020305.fst',
 'huc_1704020406.fst',
 'huc_1704020603.fst',
 'huc_1704020610.fst',
 'huc_1704020803.fst',
 'huc_1704020904.fst',
 'huc_1704020906.fst',
 'huc_1704020913.fst',
 'huc_1704021009.fst',
 'huc_1704021104.fst',
 'huc_1704021205.fst',
 'huc_1704021206.fst',
 'huc_1704021301.fst',
 'huc_1704021406.fst',
 'huc_1704021705.fst',
 'huc_1704021902.fst',
 'huc_1704021907.fst',
 'huc_1704022001.fst',
 'huc_1704022004.fst',
 'huc_1704022104.fst',
 'huc_1704022105.fst',
 'huc_1704022106.fst',
 'huc_1705010106.fst',
 'huc_1705010108.fst',
 'huc_1705010212.fst',
 'huc_1705010310.fst',
 'huc_1705010401.fst',
 'huc_1705010406.fst',
 'huc_1705010413.fst',
 'huc_1705010416.fst',
 'huc_1705010606.fst',
 'huc_1705010702.fst',
 'huc_1705010801.fst',
 'huc_1705010807.fst',
 'huc_1705010904.fst',
 'huc_1705011007.fst',
 'huc_1705011307.fst',
 'huc_1705011310.fst',
 'huc_1705011401.fst',
 'huc_1705011403.fst',
 'huc_1705011404.fst',
 'huc_1705011408.fst',
 'huc_1705011602.fst',
 'huc_1705011603.fst',
 'huc_1705011609.fst',
 'huc_1705011610.fst',
 'huc_1705011611.fst',
 'huc_1705011612.fst',
 'huc_1705011613.fst',
 'huc_1705011614.fst',
 'huc_1705011701.fst',
 'huc_1705011702.fst',
 'huc_1705011703.fst',
 'huc_1705011704.fst',
 'huc_1705011705.fst',
 'huc_1705011706.fst',
 'huc_1705011801.fst',
 'huc_1705011802.fst',
 'huc_1705011803.fst',
 'huc_1705011901.fst',
 'huc_1705011902.fst',
 'huc_1705011904.fst',
 'huc_1705011905.fst',
 'huc_1705011906.fst',
 'huc_1705012001.fst',
 'huc_1705012002.fst',
 'huc_1705012003.fst',
 'huc_1705012004.fst',
 'huc_1705012005.fst',
 'huc_1705012006.fst',
 'huc_1705012101.fst',
 'huc_1705012103.fst',
 'huc_1705012104.fst',
 'huc_1705012201.fst',
 'huc_1705012202.fst',
 'huc_1705012203.fst',
 'huc_1705012204.fst',
 'huc_1705012205.fst',
 'huc_1705012206.fst',
 'huc_1705012207.fst',
 'huc_1705012208.fst',
 'huc_1705012209.fst',
 'huc_1705012301.fst',
 'huc_1705012302.fst',
 'huc_1705012303.fst',
 'huc_1705012304.fst',
 'huc_1705012305.fst',
 'huc_1705012306.fst',
 'huc_1705012401.fst',
 'huc_1705012402.fst',
 'huc_1705012403.fst',
 'huc_1705012405.fst',
 'huc_1705012406.fst',
 'huc_1705012407.fst',
 'huc_1705012408.fst',
 'huc_1705012411.fst',
 'huc_1705020101.fst',
 'huc_1705020102.fst',
 'huc_1705020103.fst',
 'huc_1705020104.fst',
 'huc_1705020105.fst',
 'huc_1705020107.fst',
 'huc_1705020201.fst',
 'huc_1705020202.fst',
 'huc_1705020203.fst',
 'huc_1705020204.fst',
 'huc_1705020205.fst',
 'huc_1705020206.fst',
 'huc_1705020207.fst',
 'huc_1705020208.fst',
 'huc_1705020301.fst',
 'huc_1705020302.fst',
 'huc_1705020303.fst',
 'huc_1705020304.fst',
 'huc_1705020305.fst',
 'huc_1705020306.fst',
 'huc_1705020308.fst',
 'huc_1705020309.fst',
 'huc_1705020310.fst',
 'huc_1705020311.fst',
 'huc_1706010102.fst',
 'huc_1706010103.fst',
 'huc_1706010201.fst',
 'huc_1706010202.fst',
 'huc_1706010203.fst',
 'huc_1706010204.fst',
 'huc_1706010205.fst',
 'huc_1706010301.fst',
 'huc_1706010302.fst',
 'huc_1706010303.fst',
 'huc_1706010401.fst',
 'huc_1706010402.fst',
 'huc_1706010403.fst',
 'huc_1706010404.fst',
 'huc_1706010405.fst',
 'huc_1706010406.fst',
 'huc_1706010407.fst',
 'huc_1706010409.fst',
 'huc_1706010410.fst',
 'huc_1706010411.fst',
 'huc_1706010501.fst',
 'huc_1706010502.fst',
 'huc_1706010503.fst',
 'huc_1706010504.fst',
 'huc_1706010505.fst',
 'huc_1706010506.fst',
 'huc_1706010601.fst',
 'huc_1706010602.fst',
 'huc_1706010603.fst',
 'huc_1706010604.fst',
 'huc_1706010605.fst',
 'huc_1706010606.fst',
 'huc_1706010607.fst',
 'huc_1706010701.fst',
 'huc_1706010702.fst',
 'huc_1706010703.fst',
 'huc_1706010705.fst',
 'huc_1706010706.fst',
 'huc_1706010707.fst',
 'huc_1706010708.fst',
 'huc_1706010801.fst',
 'huc_1706010802.fst',
 'huc_1706010803.fst',
 'huc_1706010805.fst',
 'huc_1706010806.fst',
 'huc_1706010807.fst',
 'huc_1706010808.fst',
 'huc_1706010901.fst',
 'huc_1706010902.fst',
 'huc_1706010903.fst',
 'huc_1706011001.fst',
 'huc_1706011003.fst',
 'huc_1706020101.fst',
 'huc_1706020102.fst',
 'huc_1706020103.fst',
 'huc_1706020104.fst',
 'huc_1706020105.fst',
 'huc_1706020106.fst',
 'huc_1706020108.fst',
 'huc_1706020109.fst',
 'huc_1706020111.fst',
 'huc_1706020112.fst',
 'huc_1706020113.fst',
 'huc_1706020304.fst',
 'huc_1706020406.fst',
 'huc_1706020501.fst',
 'huc_1706020508.fst',
 'huc_1706020511.fst',
 'huc_1706020603.fst',
 'huc_1706020703.fst',
 'huc_1706020709.fst',
 'huc_1706020710.fst',
 'huc_1706020902.fst',
 'huc_1706020907.fst',
 'huc_1706021003.fst',
 'huc_1706021004.fst',
 'huc_1706021005.fst',
 'huc_1706030101.fst',
 'huc_1706030102.fst',
 'huc_1706030103.fst',
 'huc_1706030104.fst',
 'huc_1706030106.fst',
 'huc_1706030107.fst',
 'huc_1706030201.fst',
 'huc_1706030202.fst',
 'huc_1706030203.fst',
 'huc_1706030204.fst',
 'huc_1706030301.fst',
 'huc_1706030302.fst',
 'huc_1706030305.fst',
 'huc_1706030306.fst',
 'huc_1706030307.fst',
 'huc_1706030401.fst',
 'huc_1706030402.fst',
 'huc_1706030501.fst',
 'huc_1706030502.fst',
 'huc_1706030504.fst',
 'huc_1706030505.fst',
 'huc_1706030506.fst',
 'huc_1706030507.fst',
 'huc_1706030508.fst',
 'huc_1706030509.fst',
 'huc_1706030601.fst',
 'huc_1706030602.fst',
 'huc_1706030603.fst',
 'huc_1706030604.fst',
 'huc_1706030605.fst',
 'huc_1706030606.fst',
 'huc_1706030608.fst',
 'huc_1706030609.fst',
 'huc_1706030610.fst',
 'huc_1706030611.fst',
 'huc_1706030612.fst',
 'huc_1706030613.fst',
 'huc_1706030701.fst',
 'huc_1706030702.fst',
 'huc_1706030704.fst',
 'huc_1706030705.fst',
 'huc_1706030706.fst',
 'huc_1706030707.fst',
 'huc_1706030708.fst',
 'huc_1706030709.fst',
 'huc_1706030710.fst',
 'huc_1706030801.fst',
 'huc_1706030802.fst',
 'huc_1706030803.fst',
 'huc_1706030804.fst',
 'huc_1706030805.fst',
 'huc_1706030806.fst',
 'huc_1706030807.fst',
 'huc_1706030808.fst']

In [12]:
subdirs

['DATA/Inputs/gcms/predictions_covariates/CanESM2/',
 'DATA/Inputs/gcms/predictions_covariates/CCSM4/',
 'DATA/Inputs/gcms/predictions_covariates/CNRM-CM5/',
 'DATA/Inputs/gcms/predictions_covariates/CSIRO-Mk3-6-0/',
 'DATA/Inputs/gcms/predictions_covariates/GDFL-ESM2M/',
 'DATA/Inputs/gcms/predictions_covariates/HadGEM2-CC/',
 'DATA/Inputs/gcms/predictions_covariates/HadGEM2-ES/',
 'DATA/Inputs/gcms/predictions_covariates/inmcm4/',
 'DATA/Inputs/gcms/predictions_covariates/IPSL-CM5A-MR/',
 'DATA/Inputs/gcms/predictions_covariates/MIROC/']

In [14]:
%%time
fail_list = []
for file in files_to_do[2:]:
    huc = file[-14:-4]
    outfile = os.path.join(dir_to_do, 'parquets', f'{huc}_covs.parq')
    print(huc)

    for gcm in subdirs:
        curfile = os.path.join(gcm, file)
        try: 
            df = ro.r(f"read.fst('{curfile}')")
            ddf = dd.from_pandas(df)
            ddf['GCM'] = gcm_dict[gcm.split('/')[-2]]
            if os.path.exists(outfile):
                ddf.to_parquet(outfile, engine='pyarrow', append=True, write_index = False, compression = 'gzip')
                #print('appended', gcm_dict[gcm.split('/')[-2]])
            else:
                ddf.to_parquet(outfile, engine='pyarrow', write_index = False, compression = 'gzip')
                #print('written', gcm_dict[gcm.split('/')[-2]])
            os.remove(curfile)
            
        except: 
            print('error')
            fail_list.append(curfile)
            continue 
            
    print("(Files removed)")

R[write to console]: fstcore package v0.9.18

R[write to console]: (OpenMP detected, using 16 threads)

1701010117
(Files removed)
1701010304
(Files removed)
1701010305
(Files removed)
1701010401
(Files removed)
1701010404
(Files removed)
1701010406
(Files removed)
1701010407
(Files removed)
1701010504
(Files removed)
1701010505
(Files removed)
1701020102
(Files removed)
1701020211
(Files removed)
1701020213
(Files removed)
1701020406
(Files removed)
1701020507
(Files removed)
1701020605
(Files removed)
1701020606
(Files removed)
1701020701
(Files removed)
1701020702
(Files removed)
1701020703
(Files removed)
1701020704
(Files removed)
1701020705
(Files removed)
1701020801
(Files removed)
1701020802
(Files removed)
1701020803
(Files removed)
1701020804
(Files removed)
1701020901
(Files removed)
1701020902
(Files removed)
1701020903
(Files removed)
1701020905
(Files removed)
1701020906
(Files removed)
1701020907
(Files removed)
1701021001
(Files removed)
1701021003
(Files removed)
1701021004
(Files removed)
1701021005
(Files removed)
1701021101
(Files removed)
1701021102
(Files removed)
1701021103
(Files removed)
1701021104
(Files removed)
1701021201
(Files removed)
1701021202
(Files removed)
1701021203
(Files removed)
1701021204
(Files removed)
1701021206
(Files removed)
1701021207
(Files removed)
1701021208
(Files removed)
1701021301
(Files removed)
1701021302
(Files removed)
1701021303
(Files removed)
1701021304
(Files removed)
1701021305
(Files removed)
1701021306
(Files removed)
1701021309
(Files removed)
1701021310
(Files removed)
1701021311
(Files removed)
1701021312
(Files removed)
1701021313
(Files removed)
1701021401
(Files removed)
1701021402
(Files removed)
1701021502
(Files removed)
1701021503
(Files removed)
1701021604
(Files removed)
1701021609
(Files removed)
1701030202
(Files removed)
1701030406
(Files removed)
1702000110
(Files removed)
1702000111
(Files removed)
1702000112
(Files removed)
1702000113
(Files removed)
1702000114
(Files removed)
1702000115
(Files removed)
1702000116
(Files removed)
1702000117
(Files removed)
1702000119
(Files removed)
1702000209
(Files removed)
1702000212
(Files removed)
1702000213
(Files removed)
1702000217
(Files removed)
1702000219
(Files removed)
1702000220
(Files removed)
1702000303
(Files removed)
1702000401
(Files removed)
1702000615
(Files removed)
1702000618
(Files removed)
1702000619
(Files removed)
1702000620
(Files removed)
1702000621
(Files removed)
1702000622
(Files removed)
1702000701
(Files removed)
1702000713
(Files removed)
1702000718
(Files removed)
1702000719
(Files removed)
1702000720
(Files removed)
1702000806
(Files removed)
1702000807
(Files removed)
1702001106
(Files removed)
1702001307
(Files removed)
1702001401
(Files removed)
1702001403
(Files removed)
1702001509
(Files removed)
1702001510
(Files removed)
1702001606
(Files removed)
1703000105
(Files removed)
1703000201
(Files removed)
1703000203
(Files removed)
1703000305
(Files removed)
1704010302
(Files removed)
1704010401
(Files removed)
1704010403
(Files removed)
1704010404
(Files removed)
1704010407
(Files removed)
1704010409
(Files removed)
1704020103
(Files removed)
1704020202
(Files removed)
1704020205
(Files removed)
1704020207
(Files removed)
1704020305
(Files removed)
1704020406
(Files removed)
1704020603
(Files removed)
1704020610
(Files removed)
1704020803
(Files removed)
1704020904
(Files removed)
1704020906
(Files removed)
1704020913
(Files removed)
1704021009
(Files removed)
1704021104
(Files removed)
1704021205
(Files removed)
1704021206
(Files removed)
1704021301
(Files removed)
1704021406
(Files removed)
1704021705
(Files removed)
1704021902
(Files removed)
1704021907
(Files removed)
1704022001
(Files removed)
1704022004
(Files removed)
1704022104
(Files removed)
1704022105
(Files removed)
1704022106
(Files removed)
1705010106
(Files removed)
1705010108
(Files removed)
1705010212
(Files removed)
1705010310
(Files removed)
1705010401
(Files removed)
1705010406
(Files removed)
1705010413
(Files removed)
1705010416
(Files removed)
1705010606
(Files removed)
1705010702
(Files removed)
1705010801
(Files removed)
1705010807
(Files removed)
1705010904
(Files removed)
1705011007
(Files removed)
1705011307
(Files removed)
1705011310
(Files removed)
1705011401
(Files removed)
1705011403
(Files removed)
1705011404
(Files removed)
1705011408
(Files removed)
1705011602
(Files removed)
1705011603
(Files removed)
1705011609
(Files removed)
1705011610
(Files removed)
1705011611
(Files removed)
1705011612
(Files removed)
1705011613
(Files removed)
1705011614
(Files removed)
1705011701
(Files removed)
1705011702
(Files removed)
1705011703
(Files removed)
1705011704
(Files removed)
1705011705
(Files removed)
1705011706
(Files removed)
1705011801
(Files removed)
1705011802
(Files removed)
1705011803
(Files removed)
1705011901
(Files removed)
1705011902
(Files removed)
1705011904
(Files removed)
1705011905
(Files removed)
1705011906
(Files removed)
1705012001
(Files removed)
1705012002
(Files removed)
1705012003
(Files removed)
1705012004
(Files removed)
1705012005
(Files removed)
1705012006
(Files removed)
1705012101
(Files removed)
1705012103
(Files removed)
1705012104
(Files removed)
1705012201
(Files removed)
1705012202
(Files removed)
1705012203
(Files removed)
1705012204
(Files removed)
1705012205
(Files removed)
1705012206
(Files removed)
1705012207
(Files removed)
1705012208
(Files removed)
1705012209
(Files removed)
1705012301
(Files removed)
1705012302
(Files removed)
1705012303
(Files removed)
1705012304
(Files removed)
1705012305
(Files removed)
1705012306
(Files removed)
1705012401
(Files removed)
1705012402
(Files removed)
1705012403
(Files removed)
1705012405
(Files removed)
1705012406
(Files removed)
1705012407
(Files removed)
1705012408
(Files removed)
1705012411
(Files removed)
1705020101
(Files removed)
1705020102
(Files removed)
1705020103
(Files removed)
1705020104
(Files removed)
1705020105
(Files removed)
1705020107
(Files removed)
1705020201
(Files removed)
1705020202
(Files removed)
1705020203
(Files removed)
1705020204
(Files removed)
1705020205
(Files removed)
1705020206
(Files removed)
1705020207
(Files removed)
1705020208
(Files removed)
1705020301
(Files removed)
1705020302
(Files removed)
1705020303
(Files removed)
1705020304
(Files removed)
1705020305
(Files removed)
1705020306
(Files removed)
1705020308
(Files removed)
1705020309
(Files removed)
1705020310
(Files removed)
1705020311
(Files removed)
1706010102
(Files removed)
1706010103
(Files removed)
1706010201
(Files removed)
1706010202
(Files removed)
1706010203
(Files removed)
1706010204
(Files removed)
1706010205
(Files removed)
1706010301
(Files removed)
1706010302
(Files removed)
1706010303
(Files removed)
1706010401
(Files removed)
1706010402
(Files removed)
1706010403
(Files removed)
1706010404
(Files removed)
1706010405
(Files removed)
1706010406
(Files removed)
1706010407
(Files removed)
1706010409
(Files removed)
1706010410
(Files removed)
1706010411
(Files removed)
1706010501
(Files removed)
1706010502
(Files removed)
1706010503
(Files removed)
1706010504
(Files removed)
1706010505
(Files removed)
1706010506
(Files removed)
1706010601
(Files removed)
1706010602
(Files removed)
1706010603
(Files removed)
1706010604
(Files removed)
1706010605
(Files removed)
1706010606
(Files removed)
1706010607
(Files removed)
1706010701
(Files removed)
1706010702
(Files removed)
1706010703
(Files removed)
1706010705
(Files removed)
1706010706
(Files removed)
1706010707
(Files removed)
1706010708
(Files removed)
1706010801
(Files removed)
1706010802
(Files removed)
1706010803
(Files removed)
1706010805
(Files removed)
1706010806
(Files removed)
1706010807
(Files removed)
1706010808
(Files removed)
1706010901
(Files removed)
1706010902
(Files removed)
1706010903
(Files removed)
1706011001
(Files removed)
1706011003
(Files removed)
1706020101
(Files removed)
1706020102
(Files removed)
1706020103
(Files removed)
1706020104
(Files removed)
1706020105
(Files removed)
1706020106
(Files removed)
1706020108
(Files removed)
1706020109
(Files removed)
1706020111
(Files removed)
1706020112
(Files removed)
1706020113
(Files removed)
1706020304
(Files removed)
1706020406
(Files removed)
1706020501
(Files removed)
1706020508
(Files removed)
1706020511
(Files removed)
1706020603
(Files removed)
1706020703
(Files removed)
1706020709
(Files removed)
1706020710
(Files removed)
1706020902
(Files removed)
1706020907
(Files removed)
1706021003
(Files removed)
1706021004
(Files removed)
1706021005
(Files removed)
1706030101
(Files removed)
1706030102
(Files removed)
1706030103
(Files removed)
1706030104
(Files removed)
1706030106
(Files removed)
1706030107
(Files removed)
1706030201
(Files removed)
1706030202
(Files removed)
1706030203
(Files removed)
1706030204
(Files removed)
1706030301
(Files removed)
1706030302
(Files removed)
1706030305
(Files removed)
1706030306
(Files removed)
1706030307
(Files removed)
1706030401
(Files removed)
1706030402
(Files removed)
1706030501
(Files removed)
1706030502
(Files removed)
1706030504
(Files removed)
1706030505
(Files removed)
1706030506
(Files removed)
1706030507
(Files removed)
1706030508
(Files removed)
1706030509
(Files removed)
1706030601
(Files removed)
1706030602
(Files removed)
1706030603
(Files removed)
1706030604
(Files removed)
1706030605
(Files removed)
1706030606
(Files removed)
1706030608
(Files removed)
1706030609
(Files removed)
1706030610
(Files removed)
1706030611
(Files removed)
1706030612
(Files removed)
1706030613
(Files removed)
1706030701
(Files removed)
1706030702
(Files removed)
1706030704
(Files removed)
1706030705
(Files removed)
1706030706
(Files removed)
1706030707
(Files removed)
1706030708
(Files removed)
1706030709
(Files removed)
1706030710
(Files removed)
1706030801
(Files removed)
1706030802
(Files removed)
1706030803
(Files removed)
1706030804
(Files removed)
1706030805
(Files removed)
1706030806
(Files removed)
1706030807
(Files removed)
1706030808
(Files removed)
CPU times: user 23h 8min 22s, sys: 2h 50min 29s, total: 1d 1h 58min 51s
Wall time: 19h 21min 33s

In [13]:
ddf = dd.read_parquet(outfile)
ddf

Dask DataFrame Structure:
                COMID  SegID  lookup cov.air_temp cov.air_temp_ws cov.air_temp_3d cov.air_temp_6d cov.air_temp_9d cov.air_temp_12d cov.air_temp_15d cov.air_temp_18d cov.air_temp_21d cov.air_temp_24d cov.air_temp_27d cov.air_temp_30d cov.air_temp_35d cov.air_temp_40d cov.air_temp_50d cov.air_temp_60d  cov.SWE cov.SWE_ws cov.Flow cov.Flow_log tim.year  tim.doy tim.date cov.daylength cov.daylength_hours cov.SWE_mean_year cov.SWE_1Apr cov.SWE_last_doy    GCM
npartitions=10
                int64  int64  string      float64         float64         float64         float64         float64          float64          float64          float64          float64          float64          float64          float64          float64          float64          float64          float64  float64    float64  float64      float64  float64  float64  float64       float64             float64           float64      float64          float64  int64
                  ...    ...     ...          ...             ...             ...             ...             ...              ...              ...              ...              ...              ...              ...              ...              ...              ...              ...              ...      ...        ...      ...          ...      ...      ...      ...           ...                 ...               ...          ...              ...    ...
...               ...    ...     ...          ...             ...             ...             ...             ...              ...              ...              ...              ...              ...              ...              ...              ...              ...              ...              ...      ...        ...      ...          ...      ...      ...      ...           ...                 ...               ...          ...              ...    ...
                  ...    ...     ...          ...             ...             ...             ...             ...              ...              ...              ...              ...              ...              ...              ...              ...              ...              ...              ...      ...        ...      ...          ...      ...      ...      ...           ...                 ...               ...          ...              ...    ...
                  ...    ...     ...          ...             ...             ...             ...             ...              ...              ...              ...              ...              ...              ...              ...              ...              ...              ...              ...      ...        ...      ...          ...      ...      ...      ...           ...                 ...               ...          ...              ...    ...
Dask Name: read_parquet, 1 expression
Expr=ReadParquetFSSpec(7fe6805)

In [71]:
os.path.exists(outfile)

True

In [15]:
len(ddf)

42733860

In [14]:
ddf.GCM.compute().unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
gcm.split('/')[-2]

'CNRM-CM5'

In [40]:
ddf.groupby(['COMID', 'lookup']).count().compute()

                      SegID  cov.air_temp  cov.air_temp_ws  cov.air_temp_3d  \
COMID    lookup
22879101 10_1950_1        1             1                1                0
         10_1950_10       1             1                1                1
         10_1950_100      1             1                1                1
         10_1950_101      1             1                1                1
         10_1950_102      1             1                1                1
...                     ...           ...              ...              ...
22880853 46_2099_95       1             1                1                1
         46_2099_96       1             1                1                1
         46_2099_97       1             1                1                1
         46_2099_98       1             1                1                1
         46_2099_99       1             1                1                1

                      cov.air_temp_6d  cov.air_temp_9d  cov.air_temp_12d  \
COMID    lookup
22879101 10_1950_1                  0                0                 0
         10_1950_10                 1                1                 0
         10_1950_100                1                1                 1
         10_1950_101                1                1                 1
         10_1950_102                1                1                 1
...                               ...              ...               ...
22880853 46_2099_95                 1                1                 1
         46_2099_96                 1                1                 1
         46_2099_97                 1                1                 1
         46_2099_98                 1                1                 1
         46_2099_99                 1                1                 1

                      cov.air_temp_15d  cov.air_temp_18d  cov.air_temp_21d  \
COMID    lookup
22879101 10_1950_1                   0                 0                 0
         10_1950_10                  0                 0                 0
         10_1950_100                 1                 1                 1
         10_1950_101                 1                 1                 1
         10_1950_102                 1                 1                 1
...                                ...               ...               ...
22880853 46_2099_95                  1                 1                 1
         46_2099_96                  1                 1                 1
         46_2099_97                  1                 1                 1
         46_2099_98                  1                 1                 1
         46_2099_99                  1                 1                 1

                      ...  cov.Flow  cov.Flow_log  tim.year  tim.doy  \
COMID    lookup       ...
22879101 10_1950_1    ...         1             1         1        1
         10_1950_10   ...         1             1         1        1
         10_1950_100  ...         1             1         1        1
         10_1950_101  ...         1             1         1        1
         10_1950_102  ...         1             1         1        1
...                   ...       ...           ...       ...      ...
22880853 46_2099_95   ...         1             1         1        1
         46_2099_96   ...         1             1         1        1
         46_2099_97   ...         1             1         1        1
         46_2099_98   ...         1             1         1        1
         46_2099_99   ...         1             1         1        1

                      tim.date  cov.daylength  cov.daylength_hours  \
COMID    lookup
22879101 10_1950_1           1              1                    1
         10_1950_10          1              1                    1
         10_1950_100         1              1                    1
         10_1950_101         1              1                    1
         10_1950_102         1              1                    1
...                        ...            ...                  ...
22880853 46_2099_95          1              1                    1
         46_2099_96          1              1                    1
         46_2099_97          1              1                    1
         46_2099_98          1              1                    1
         46_2099_99          1              1                    1

                      cov.SWE_mean_year  cov.SWE_1Apr  cov.SWE_last_doy
COMID    lookup
22879101 10_1950_1                    1             1                 1
         10_1950_10                   1             1                 1
         10_1950_100                  1             1                 1
         10_1950_101                  1             1                 1
         10_1950_102                  1             1                 1
...                                 ...           ...               ...
22880853 46_2099_95                   1             1                 1
         46_2099_96                   1             1                 1
         46_2099_97                   1             1                 1
         46_2099_98                   1             1                 1
         46_2099_99                   1             1                 1

[1150527 rows x 29 columns]

In [27]:
for col in df.columns:
    if df[col].dtype == np.str_:  # Check if the column is numpy.str_
        print(col)
        df[col] = df[col].astype(object)

In [29]:
df.to_parquet(outfile, engine='pyarrow')

In [30]:
if os.path.isfile(outfile):
  df.to_parquet(outfile, engine='pyarrow', append=True)
else:
  df.to_parquet(outfile, engine='pyarrow')

TypeError: __cinit__() got an unexpected keyword argument 'append'

In [19]:
df.to_parquet(outfile, engine='fastparquet')

TypeError: Expected unicode, got numpy.str_

In [10]:
%%time
fail_list = []

for file in files_to_do:
    print(file)
    cur_huc = file[-14:-4]
    try: df = ro.r(f"read.fst('{file}')")
    except: fail_list.append(file)

    df['date'] = pd.to_datetime(df['tim.year'] * 1000 + df['tim.doy'], format='%Y%j')
    df.to_csv(os.path.join(temp_dir, 'DATA', 'preds_retro', 'predictions_covariates', 'cov_csvs', f'{cur_huc}_covs.zip'), index = False, compression = 'zip')

R[write to console]: fstcore package v0.9.18

R[write to console]: (OpenMP detected, using 16 threads)

/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020201.fst
/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020202.fst
/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020203.fst
/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020204.fst
/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020205.fst
/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020206.fst
/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020207.fst
/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020208.fst
/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020301.fst
/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020302.fst
/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020303.fst
/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020304.fst
/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020305.fst
/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020306.fst
/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020307.fst
/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020308.fst
/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020309.fst
/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020310.fst
/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020311.fst
/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020101.fst
/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020102.fst
/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020103.fst
/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020104.fst
/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020105.fst
/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020106.fst
/Volumes/Elements/URycki/Repos/temp-data/DATA/preds_retro/predictions_covariates/recovered/huc_1705020107.fst
CPU times: user 36min 24s, sys: 12min 50s, total: 49min 15s
Wall time: 32min 41s